# config
logo: /images/svdb.png
keywords: "jackson wheeler, developer, blog, santa clara, santa clara university"
menu:
  Home: /
  Project Entries: /articles
  Main Website: https://jacksonjw.com
  About Me: /about

# Content
excerpt_link: Read more

# Miscellaneous
rss: /atom.xml
google_analytics:
